# Generated by Django 2.2.4 on 2020-03-07 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compañias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_compañia', models.CharField(max_length=80)),
                ('actividad', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'sm_compañias',
            },
        ),
        migrations.CreateModel(
            name='Cuartel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('ubicacion', models.CharField(max_length=160)),
            ],
            options={
                'db_table': 'sm_cuartel',
            },
        ),
        migrations.CreateModel(
            name='Cuerpos_del_ejercito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominacion', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'sm_cuerpos_del_ejercito',
            },
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'sm_servicios',
            },
        ),
        migrations.CreateModel(
            name='Soldados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segundo_nombre', models.CharField(max_length=50)),
                ('primer_nombre', models.CharField(max_length=50)),
                ('segundo_apellido', models.CharField(max_length=50)),
                ('graduacion', models.DateTimeField(verbose_name='date published')),
            ],
            options={
                'db_table': 'sm_soldados',
            },
        ),
        migrations.CreateModel(
            name='Soldados_registrados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compañia_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='militares.Compañias')),
                ('cuartel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='militares.Cuartel')),
                ('cuerpo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='militares.Cuerpos_del_ejercito')),
                ('servicio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='militares.Servicios')),
                ('soldado_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='militares.Soldados')),
            ],
            options={
                'db_table': 'sm_soldados_registrados',
            },
        ),
    ]
