# Generated by Django 2.2.4 on 2020-03-07 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soldados_registrados',
            old_name='compañia_id',
            new_name='compañia',
        ),
        migrations.RenameField(
            model_name='soldados_registrados',
            old_name='cuartel_id',
            new_name='cuartel',
        ),
        migrations.RenameField(
            model_name='soldados_registrados',
            old_name='cuerpo_id',
            new_name='cuerpo',
        ),
        migrations.RenameField(
            model_name='soldados_registrados',
            old_name='servicio_id',
            new_name='servicio',
        ),
        migrations.RenameField(
            model_name='soldados_registrados',
            old_name='soldado_id',
            new_name='soldado',
        ),
    ]
