# Generated by Django 2.2.4 on 2020-03-07 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0002_auto_20200307_2324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compañias',
            old_name='numero_compañia',
            new_name='numero_compania',
        ),
        migrations.RenameField(
            model_name='soldados_registrados',
            old_name='compañia',
            new_name='compania',
        ),
    ]
