# Generated by Django 2.2.3 on 2020-04-04 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0005_soldado_primer_apellido'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldado',
            name='soldado',
            field=models.ForeignKey(default=45, on_delete=django.db.models.deletion.CASCADE, to='militares.Cuartel'),
            preserve_default=False,
        ),
    ]
