# Generated by Django 2.2.3 on 2020-04-04 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0006_soldado_soldado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soldado',
            old_name='soldado',
            new_name='cuartel',
        ),
    ]
