# Generated by Django 2.2.3 on 2020-04-04 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0007_auto_20200404_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldado',
            name='cedula',
            field=models.IntegerField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
